#!/bin/bash
# Sample batchscript to run an OpenMP job on HPC
#SBATCH --account=hagan-lab
#SBATCH --partition=hagan-compute               # queue to be used
#SBATCH --time=23:59:59                         # Running time (in hours-minutes-seconds)
#SBATCH --mail-type=BEGIN,END,FAIL              # send an email when the job begins, ends or fails
#SBATCH --mail-user=chaitanya@brandeis.edu      # Email address to send the job status
#SBATCH --output=output/output_%j.txt                  # Name of the output file
#SBATCH --error=error/error_%j.txt                    # Name of the error file
#SBATCH --ntasks=1                              # Number of computer nodes
